<?php
declare(strict_types=1);

function getProducts(): array
{
    return [
        'arabica' => [
            'id' => 'arabica',
            'name' => 'Signature Arabica Coffee',
            'description' => 'Medium roast with cocoa notes and smooth finish, ideal for pour-over and French press.',
            'details' => 'Single-origin Arabica beans roasted in small batches to bring out chocolate and toasted nut notes. Balanced body with a clean finish.',
            'price' => 14.99,
            'size' => '250g',
            'category' => 'coffee',
            'origin' => 'Ethiopia & Colombia',
            'brew' => 'Pour-over, French press',
            'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
        ],
        'masala-chai' => [
            'id' => 'masala-chai',
            'name' => 'Classic Masala Chai',
            'description' => 'Black tea with cardamom, cinnamon, and ginger for a comforting, spiced everyday cup.',
            'details' => 'Robust Assam tea leaves blended with traditional Indian spices for a warming cup with milk or without.',
            'price' => 10.99,
            'size' => '200g',
            'category' => 'tea',
            'origin' => 'Assam, India',
            'brew' => 'Stovetop chai, tea infuser',
            'image' => 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=900&q=80',
        ],
        'green-harmony' => [
            'id' => 'green-harmony',
            'name' => 'Green Harmony Tea',
            'description' => 'Light, fresh green tea packed with antioxidants and a crisp, calming flavor profile.',
            'details' => 'Delicate green tea leaves carefully steamed and rolled to keep freshness, giving a clean vegetal and lightly sweet cup.',
            'price' => 12.49,
            'size' => '180g',
            'category' => 'tea',
            'origin' => 'Darjeeling, India',
            'brew' => 'Tea infuser, cold brew',
            'image' => 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=80',
        ],
        'espresso-blend' => [
            'id' => 'espresso-blend',
            'name' => 'Dark Roast Espresso Blend',
            'description' => 'Bold espresso blend with deep caramelized notes for shots, lattes, and cappuccinos.',
            'details' => 'Dark roasted blend crafted for pressure brewing with dense crema, rich body, and deep cocoa finish.',
            'price' => 16.49,
            'size' => '250g',
            'category' => 'coffee',
            'origin' => 'Brazil & Vietnam',
            'brew' => 'Espresso machine, moka pot',
            'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80',
        ],
        'vanilla-latte' => [
            'id' => 'vanilla-latte',
            'name' => 'Vanilla Latte Blend',
            'description' => 'Smooth coffee blend with a subtle vanilla aroma, perfect for milk-based drinks.',
            'details' => 'Aromatic medium-dark roast designed for creamy lattes and iced coffee with sweet vanilla notes.',
            'price' => 15.49,
            'size' => '250g',
            'category' => 'coffee',
            'origin' => 'Colombia',
            'brew' => 'Espresso machine, moka pot',
            'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80',
        ],
        'morning-mocha' => [
            'id' => 'morning-mocha',
            'name' => 'Morning Mocha Roast',
            'description' => 'Chocolate-forward roast with full body and gentle acidity for an energetic start.',
            'details' => 'Carefully blended beans with deep cocoa character and rounded sweetness in every cup.',
            'price' => 17.29,
            'size' => '250g',
            'category' => 'coffee',
            'origin' => 'Brazil',
            'brew' => 'Drip coffee, French press',
            'image' => 'https://images.unsplash.com/photo-1494314671902-399b18174975?auto=format&fit=crop&w=900&q=80',
        ],
        'earl-grey' => [
            'id' => 'earl-grey',
            'name' => 'Royal Earl Grey Tea',
            'description' => 'Fragrant black tea infused with bergamot for a bright citrus aroma.',
            'details' => 'Classic Earl Grey crafted with high-grade tea leaves and natural bergamot essence.',
            'price' => 11.99,
            'size' => '180g',
            'category' => 'tea',
            'origin' => 'Sri Lanka',
            'brew' => 'Tea infuser, teapot',
            'image' => 'https://images.unsplash.com/photo-1492778297155-7be4c83960c2?auto=format&fit=crop&w=900&q=80',
        ],
        'herbal-calm' => [
            'id' => 'herbal-calm',
            'name' => 'Herbal Calm Infusion',
            'description' => 'Caffeine-free blend with chamomile and mint for a soothing evening cup.',
            'details' => 'A relaxing herbal infusion made for calm evenings and gentle digestion support.',
            'price' => 13.49,
            'size' => '160g',
            'category' => 'tea',
            'origin' => 'India',
            'brew' => 'Tea infuser, hot steep',
            'image' => 'https://images.unsplash.com/photo-1547825407-2d060104b7f8?auto=format&fit=crop&w=900&q=80',
        ],
    ];
}
